services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paygate_api
    restart: always
    ports:
      - "5076:8080"
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080